// Code generated by protoc-gen-go.
// source: superstellar.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	superstellar.proto

It has these top-level messages:
	Message
	Point
	Vector
	Spaceship
	ProjectileFired
	PlayerLeft
	Space
	Hello
	UserMessage
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserInput int32

const (
	UserInput_CENTER     UserInput = 0
	UserInput_LEFT       UserInput = 1
	UserInput_RIGHT      UserInput = 2
	UserInput_THRUST_ON  UserInput = 3
	UserInput_THRUST_OFF UserInput = 4
	UserInput_FIRE_START UserInput = 5
	UserInput_FIRE_STOP  UserInput = 6
)

var UserInput_name = map[int32]string{
	0: "CENTER",
	1: "LEFT",
	2: "RIGHT",
	3: "THRUST_ON",
	4: "THRUST_OFF",
	5: "FIRE_START",
	6: "FIRE_STOP",
}
var UserInput_value = map[string]int32{
	"CENTER":     0,
	"LEFT":       1,
	"RIGHT":      2,
	"THRUST_ON":  3,
	"THRUST_OFF": 4,
	"FIRE_START": 5,
	"FIRE_STOP":  6,
}

func (x UserInput) String() string {
	return proto.EnumName(UserInput_name, int32(x))
}
func (UserInput) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Message struct {
	// Types that are valid to be assigned to Content:
	//	*Message_Space
	//	*Message_Hello
	//	*Message_PlayerLeft
	//	*Message_ProjectileFired
	Content isMessage_Content `protobuf_oneof:"content"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isMessage_Content interface {
	isMessage_Content()
}

type Message_Space struct {
	Space *Space `protobuf:"bytes,1,opt,name=space,oneof"`
}
type Message_Hello struct {
	Hello *Hello `protobuf:"bytes,2,opt,name=hello,oneof"`
}
type Message_PlayerLeft struct {
	PlayerLeft *PlayerLeft `protobuf:"bytes,3,opt,name=playerLeft,oneof"`
}
type Message_ProjectileFired struct {
	ProjectileFired *ProjectileFired `protobuf:"bytes,4,opt,name=projectileFired,oneof"`
}

func (*Message_Space) isMessage_Content()           {}
func (*Message_Hello) isMessage_Content()           {}
func (*Message_PlayerLeft) isMessage_Content()      {}
func (*Message_ProjectileFired) isMessage_Content() {}

func (m *Message) GetContent() isMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Message) GetSpace() *Space {
	if x, ok := m.GetContent().(*Message_Space); ok {
		return x.Space
	}
	return nil
}

func (m *Message) GetHello() *Hello {
	if x, ok := m.GetContent().(*Message_Hello); ok {
		return x.Hello
	}
	return nil
}

func (m *Message) GetPlayerLeft() *PlayerLeft {
	if x, ok := m.GetContent().(*Message_PlayerLeft); ok {
		return x.PlayerLeft
	}
	return nil
}

func (m *Message) GetProjectileFired() *ProjectileFired {
	if x, ok := m.GetContent().(*Message_ProjectileFired); ok {
		return x.ProjectileFired
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_Space)(nil),
		(*Message_Hello)(nil),
		(*Message_PlayerLeft)(nil),
		(*Message_ProjectileFired)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// content
	switch x := m.Content.(type) {
	case *Message_Space:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Space); err != nil {
			return err
		}
	case *Message_Hello:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Hello); err != nil {
			return err
		}
	case *Message_PlayerLeft:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PlayerLeft); err != nil {
			return err
		}
	case *Message_ProjectileFired:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ProjectileFired); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Content has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 1: // content.space
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Space)
		err := b.DecodeMessage(msg)
		m.Content = &Message_Space{msg}
		return true, err
	case 2: // content.hello
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Hello)
		err := b.DecodeMessage(msg)
		m.Content = &Message_Hello{msg}
		return true, err
	case 3: // content.playerLeft
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PlayerLeft)
		err := b.DecodeMessage(msg)
		m.Content = &Message_PlayerLeft{msg}
		return true, err
	case 4: // content.projectileFired
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ProjectileFired)
		err := b.DecodeMessage(msg)
		m.Content = &Message_ProjectileFired{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// content
	switch x := m.Content.(type) {
	case *Message_Space:
		s := proto.Size(x.Space)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Hello:
		s := proto.Size(x.Hello)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PlayerLeft:
		s := proto.Size(x.PlayerLeft)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ProjectileFired:
		s := proto.Size(x.ProjectileFired)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Point struct {
	X int32 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Vector struct {
	X float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
}

func (m *Vector) Reset()                    { *m = Vector{} }
func (m *Vector) String() string            { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()               {}
func (*Vector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Spaceship struct {
	Id          uint32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Position    *Point  `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	Velocity    *Vector `protobuf:"bytes,3,opt,name=velocity" json:"velocity,omitempty"`
	Facing      float32 `protobuf:"fixed32,4,opt,name=facing" json:"facing,omitempty"`
	InputThrust bool    `protobuf:"varint,5,opt,name=inputThrust" json:"inputThrust,omitempty"`
	MaxHp       uint32  `protobuf:"varint,6,opt,name=maxHp" json:"maxHp,omitempty"`
	Hp          uint32  `protobuf:"varint,7,opt,name=hp" json:"hp,omitempty"`
}

func (m *Spaceship) Reset()                    { *m = Spaceship{} }
func (m *Spaceship) String() string            { return proto.CompactTextString(m) }
func (*Spaceship) ProtoMessage()               {}
func (*Spaceship) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Spaceship) GetPosition() *Point {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Spaceship) GetVelocity() *Vector {
	if m != nil {
		return m.Velocity
	}
	return nil
}

type ProjectileFired struct {
	Id       uint32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FrameId  uint32  `protobuf:"varint,2,opt,name=frameId" json:"frameId,omitempty"`
	Origin   *Point  `protobuf:"bytes,3,opt,name=origin" json:"origin,omitempty"`
	Velocity *Vector `protobuf:"bytes,4,opt,name=velocity" json:"velocity,omitempty"`
	Facing   float32 `protobuf:"fixed32,5,opt,name=facing" json:"facing,omitempty"`
	Ttl      uint32  `protobuf:"varint,6,opt,name=ttl" json:"ttl,omitempty"`
}

func (m *ProjectileFired) Reset()                    { *m = ProjectileFired{} }
func (m *ProjectileFired) String() string            { return proto.CompactTextString(m) }
func (*ProjectileFired) ProtoMessage()               {}
func (*ProjectileFired) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ProjectileFired) GetOrigin() *Point {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *ProjectileFired) GetVelocity() *Vector {
	if m != nil {
		return m.Velocity
	}
	return nil
}

type PlayerLeft struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *PlayerLeft) Reset()                    { *m = PlayerLeft{} }
func (m *PlayerLeft) String() string            { return proto.CompactTextString(m) }
func (*PlayerLeft) ProtoMessage()               {}
func (*PlayerLeft) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Space struct {
	PhysicsFrameID uint32       `protobuf:"varint,1,opt,name=physicsFrameID" json:"physicsFrameID,omitempty"`
	Spaceships     []*Spaceship `protobuf:"bytes,2,rep,name=spaceships" json:"spaceships,omitempty"`
}

func (m *Space) Reset()                    { *m = Space{} }
func (m *Space) String() string            { return proto.CompactTextString(m) }
func (*Space) ProtoMessage()               {}
func (*Space) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Space) GetSpaceships() []*Spaceship {
	if m != nil {
		return m.Spaceships
	}
	return nil
}

type Hello struct {
	MyId uint32 `protobuf:"varint,1,opt,name=myId" json:"myId,omitempty"`
}

func (m *Hello) Reset()                    { *m = Hello{} }
func (m *Hello) String() string            { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()               {}
func (*Hello) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type UserMessage struct {
	UserInput UserInput `protobuf:"varint,1,opt,name=userInput,enum=superstellar.UserInput" json:"userInput,omitempty"`
}

func (m *UserMessage) Reset()                    { *m = UserMessage{} }
func (m *UserMessage) String() string            { return proto.CompactTextString(m) }
func (*UserMessage) ProtoMessage()               {}
func (*UserMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*Message)(nil), "superstellar.Message")
	proto.RegisterType((*Point)(nil), "superstellar.Point")
	proto.RegisterType((*Vector)(nil), "superstellar.Vector")
	proto.RegisterType((*Spaceship)(nil), "superstellar.Spaceship")
	proto.RegisterType((*ProjectileFired)(nil), "superstellar.ProjectileFired")
	proto.RegisterType((*PlayerLeft)(nil), "superstellar.PlayerLeft")
	proto.RegisterType((*Space)(nil), "superstellar.Space")
	proto.RegisterType((*Hello)(nil), "superstellar.Hello")
	proto.RegisterType((*UserMessage)(nil), "superstellar.UserMessage")
	proto.RegisterEnum("superstellar.UserInput", UserInput_name, UserInput_value)
}

func init() { proto.RegisterFile("superstellar.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x97, 0x34, 0x49, 0x9b, 0xb3, 0x7f, 0x91, 0x99, 0x20, 0x12, 0x20, 0x4d, 0x01, 0x21,
	0x04, 0xd2, 0x40, 0x20, 0x84, 0xc4, 0x1d, 0x63, 0x0d, 0x8d, 0x34, 0xb6, 0xc9, 0xcb, 0xb8, 0xe0,
	0x66, 0xca, 0x32, 0x6f, 0xf1, 0x94, 0x25, 0x56, 0xec, 0xa2, 0xe6, 0xfd, 0x78, 0x0e, 0xde, 0x82,
	0x7b, 0x6c, 0x37, 0x69, 0x9b, 0xd0, 0x1b, 0xee, 0xfc, 0x9d, 0xf3, 0x3b, 0xce, 0xf9, 0x8e, 0xed,
	0x00, 0xe2, 0x53, 0x46, 0x2a, 0x2e, 0x48, 0x9e, 0x27, 0xd5, 0x01, 0xab, 0x4a, 0x51, 0xa2, 0xad,
	0xd5, 0x58, 0xf0, 0xc7, 0x80, 0xe1, 0x37, 0xc2, 0x79, 0x72, 0x4b, 0xd0, 0x6b, 0xb0, 0x39, 0x4b,
	0x52, 0xe2, 0x1b, 0xfb, 0xc6, 0xcb, 0xcd, 0x77, 0x0f, 0x0e, 0x3a, 0xd5, 0xe7, 0x2a, 0x35, 0xd9,
	0xc0, 0x73, 0x46, 0xc1, 0x99, 0x4c, 0x94, 0xbe, 0xb9, 0x0e, 0x9e, 0xa8, 0x94, 0x82, 0x35, 0x83,
	0x3e, 0x01, 0xb0, 0x3c, 0xa9, 0x49, 0x75, 0x4c, 0x6e, 0x84, 0x3f, 0xd0, 0x15, 0x7e, 0xb7, 0xe2,
	0x6c, 0x91, 0x97, 0x65, 0x2b, 0x34, 0x8a, 0x60, 0x57, 0x36, 0x7e, 0x47, 0x52, 0x41, 0x73, 0x12,
	0xd2, 0x8a, 0x5c, 0xfb, 0x96, 0xde, 0xe0, 0x69, 0x6f, 0x83, 0x2e, 0x24, 0x77, 0xe9, 0xd7, 0x1d,
	0xba, 0x30, 0x4c, 0xcb, 0x42, 0x90, 0x42, 0x04, 0xcf, 0xc0, 0x3e, 0x2b, 0x69, 0x21, 0xd0, 0x16,
	0x18, 0x33, 0x6d, 0xd8, 0xc6, 0xc6, 0x4c, 0xa9, 0x5a, 0x3b, 0x92, 0xaa, 0x0e, 0x9e, 0x83, 0xf3,
	0x5d, 0xd6, 0x97, 0xd5, 0x92, 0x32, 0x3b, 0x94, 0xa9, 0xa8, 0xdf, 0x06, 0xb8, 0x7a, 0x38, 0x3c,
	0xa3, 0x0c, 0xed, 0x80, 0x49, 0xaf, 0x35, 0xba, 0x8d, 0xe5, 0x0a, 0xbd, 0x81, 0x11, 0x2b, 0x39,
	0x15, 0xb4, 0x2c, 0xd6, 0x8f, 0x4a, 0xb7, 0x81, 0x17, 0x10, 0x7a, 0x0b, 0xa3, 0x9f, 0x24, 0x2f,
	0x53, 0x2a, 0xea, 0x66, 0x52, 0x7b, 0xdd, 0x82, 0x79, 0x4b, 0x78, 0x41, 0xa1, 0x87, 0xe0, 0xdc,
	0x24, 0x29, 0x2d, 0x6e, 0xf5, 0x60, 0x4c, 0xdc, 0x28, 0xb4, 0x0f, 0x9b, 0xb4, 0x60, 0x53, 0x11,
	0x67, 0xd5, 0x94, 0x0b, 0xdf, 0x96, 0xc9, 0x11, 0x5e, 0x0d, 0xa1, 0x3d, 0xb0, 0xef, 0x93, 0xd9,
	0x84, 0xf9, 0x8e, 0xee, 0x77, 0x2e, 0x94, 0x85, 0x8c, 0xf9, 0xc3, 0xb9, 0x85, 0x8c, 0x05, 0xbf,
	0x0c, 0xd8, 0xed, 0x4d, 0xf7, 0x1f, 0x9b, 0x3e, 0x0c, 0x6f, 0xaa, 0xe4, 0x9e, 0x44, 0xd7, 0xda,
	0xe5, 0x36, 0x6e, 0xa5, 0xbc, 0x28, 0x4e, 0x59, 0xd1, 0x5b, 0x5a, 0x34, 0x6e, 0xd6, 0xda, 0x6f,
	0x90, 0x8e, 0x79, 0xeb, 0x3f, 0xcd, 0xdb, 0x1d, 0xf3, 0x1e, 0x0c, 0x84, 0xc8, 0x1b, 0x63, 0x6a,
	0x19, 0x3c, 0x01, 0x58, 0x5e, 0xb2, 0xbe, 0x81, 0x20, 0x03, 0x5b, 0x1f, 0x22, 0x7a, 0x01, 0x3b,
	0x2c, 0xab, 0x39, 0x4d, 0x79, 0xa8, 0x1d, 0x1c, 0x35, 0x50, 0x2f, 0x8a, 0x3e, 0x02, 0xf0, 0xf6,
	0xd4, 0xb9, 0x34, 0x3d, 0x90, 0xcd, 0x3e, 0x5a, 0xf3, 0x64, 0x54, 0x1e, 0xaf, 0xa0, 0xc1, 0x63,
	0xb0, 0xf5, 0xf3, 0x40, 0x08, 0xac, 0xfb, 0x3a, 0x6a, 0x9b, 0xd0, 0xeb, 0xe0, 0x08, 0x36, 0x2f,
	0x38, 0xa9, 0xda, 0x27, 0xf9, 0x01, 0xdc, 0xa9, 0x94, 0x91, 0x3a, 0x33, 0xcd, 0xed, 0xf4, 0xbf,
	0x71, 0xd1, 0xa6, 0xf1, 0x92, 0x7c, 0x75, 0x07, 0xee, 0x22, 0x8e, 0x00, 0x9c, 0x2f, 0xe3, 0x93,
	0x78, 0x8c, 0xbd, 0x0d, 0x34, 0x02, 0xeb, 0x78, 0x1c, 0xc6, 0x9e, 0x81, 0x5c, 0xb0, 0x71, 0xf4,
	0x75, 0x12, 0x7b, 0x26, 0xda, 0x06, 0x37, 0x9e, 0xe0, 0x8b, 0xf3, 0xf8, 0xf2, 0xf4, 0xc4, 0x1b,
	0xc8, 0xc9, 0x40, 0x2b, 0xc3, 0xd0, 0xb3, 0x94, 0x0e, 0x23, 0x3c, 0xbe, 0x3c, 0x8f, 0x3f, 0xe3,
	0xd8, 0xb3, 0x15, 0xde, 0xe8, 0xd3, 0x33, 0xcf, 0x39, 0xb4, 0x7e, 0x98, 0xec, 0xea, 0xca, 0xd1,
	0x3f, 0x97, 0xf7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xae, 0x6a, 0x47, 0x25, 0x72, 0x04, 0x00,
	0x00,
}
